[project]
name = "bookingsite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.3",
    "django-rest-framework>=0.1.0",
    "drf-yasg>=1.21.10",
]
