# Generated by Django 5.2.3 on 2025-06-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_teammember_user_alter_booking_user_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
